<template>
  <h1>
    {{$route.title}}
    <small>(template: modal.vue)</small>
  </h1>
  <div class="sample-modal">
    <a class="sample-modal-close" v-link="{ path: '../', append: true}">戻る</a>
    <div class="sample-modal-content">
      <div class="container">
        <p>あいえうを</p>
        <p>あいえうを</p>
        <p>あいえうを</p>
        <p>あいえうを</p>
        <p>あいえうを</p>
        <p>あいえうを</p>
        <p>あいえうを</p>
        <p>あいえうを</p>
        <p>あいえうを</p>
        <p>あいえうを</p>
        <p>あいえうを</p>
        <p>あいえうを</p>
        <p>あいえうを</p>
        <p>あいえうを</p>
        <p>あいえうを</p>
        <p>あいえうを</p>
        <p>あいえうを</p>
        <p>あいえうを</p>
        <p>あいえうを</p>
        <p>あいえうを</p>
        <p>あいえうを</p>
        <p>あいえうを</p>
        <p>あいえうを</p>
        <p>あいえうを</p>
        <p>あいえうを</p>
        <p>あいえうを</p>
        <p>あいえうを</p>
        <p>あいえうを</p>
        <p>あいえうを</p>
        <p>あいえうを</p>
        <p>あいえうを</p>
        <p>あいえうを</p>
        <p>あいえうを</p>
        <p>あいえうを</p>
        <p>あいえうを</p>
        <p>あいえうを</p>
        <p>あいえうを</p>
        <p>あいえうを</p>
        <p>あいえうを</p>
        <p>あいえうを</p>
        <p>あいえうを</p>
        <p>あいえうを</p>
        <p>あいえうを</p>
        <p>あいえうを</p>
        <p>あいえうを</p>
        <p>あいえうを</p>
        <p>あいえうを</p>
        <p>あいえうを</p>
        <p>あいえうを</p>
        <p>あいえうを</p>
        <p>あいえうを</p>
        <p>あいえうを</p>
        <p>あいえうを</p>
      </div>
    </div>
  </div>
</template>
